export CUDA_VISIBLE_DEVICES=0; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=3 --env_type=smooth --dataset_composition=random+optimal --cql_alpha_val=100 --transform_type=7 --const_transform=100
export CUDA_VISIBLE_DEVICES=1; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=4 --env_type=smooth --dataset_composition=random+optimal --cql_alpha_val=100 --transform_type=7 --const_transform=100
export CUDA_VISIBLE_DEVICES=2; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=5 --env_type=smooth --dataset_composition=random+optimal --cql_alpha_val=100 --transform_type=7 --const_transform=100
export CUDA_VISIBLE_DEVICES=3; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=6 --env_type=smooth --dataset_composition=random+optimal --cql_alpha_val=100 --transform_type=7 --const_transform=100
export CUDA_VISIBLE_DEVICES=4; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=3 --env_type=smooth --dataset_composition=mixed_limited --cql_alpha_val=100 --transform_type=7 --const_transform=100
export CUDA_VISIBLE_DEVICES=5; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=4 --env_type=smooth --dataset_composition=mixed_limited --cql_alpha_val=100 --transform_type=7 --const_transform=100
export CUDA_VISIBLE_DEVICES=6; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=5 --env_type=smooth --dataset_composition=mixed_limited --cql_alpha_val=100 --transform_type=7 --const_transform=100
export CUDA_VISIBLE_DEVICES=7; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=6 --env_type=smooth --dataset_composition=mixed_limited --cql_alpha_val=100 --transform_type=7 --const_transform=100

export CUDA_VISIBLE_DEVICES=0; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=3 --env_type=smooth --dataset_composition=mixed_limited_skewed --cql_alpha_val=100 --transform_type=7 --const_transform=100
export CUDA_VISIBLE_DEVICES=1; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=4 --env_type=smooth --dataset_composition=mixed_limited_skewed --cql_alpha_val=100 --transform_type=7 --const_transform=100
export CUDA_VISIBLE_DEVICES=2; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=5 --env_type=smooth --dataset_composition=mixed_limited_skewed --cql_alpha_val=100 --transform_type=7 --const_transform=100
export CUDA_VISIBLE_DEVICES=3; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=6 --env_type=smooth --dataset_composition=mixed_limited_skewed --cql_alpha_val=100 --transform_type=7 --const_transform=100
export CUDA_VISIBLE_DEVICES=4; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=3 --env_type=smooth --dataset_composition=mixed_limited_skewed --cql_alpha_val=10 --transform_type=7 --const_transform=100
export CUDA_VISIBLE_DEVICES=5; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=4 --env_type=smooth --dataset_composition=mixed_limited_skewed --cql_alpha_val=10 --transform_type=7 --const_transform=100
export CUDA_VISIBLE_DEVICES=6; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=5 --env_type=smooth --dataset_composition=mixed_limited_skewed --cql_alpha_val=10 --transform_type=7 --const_transform=100
export CUDA_VISIBLE_DEVICES=7; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=6 --env_type=smooth --dataset_composition=mixed_limited_skewed --cql_alpha_val=10 --transform_type=7 --const_transform=100

export CUDA_VISIBLE_DEVICES=0; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=3 --env_type=smooth --dataset_composition=random+optimal --cql_alpha_val=10 --transform_type=7 --const_transform=100
export CUDA_VISIBLE_DEVICES=1; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=4 --env_type=smooth --dataset_composition=random+optimal --cql_alpha_val=10 --transform_type=7 --const_transform=100
export CUDA_VISIBLE_DEVICES=2; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=5 --env_type=smooth --dataset_composition=random+optimal --cql_alpha_val=10 --transform_type=7 --const_transform=100
export CUDA_VISIBLE_DEVICES=3; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=6 --env_type=smooth --dataset_composition=random+optimal --cql_alpha_val=10 --transform_type=7 --const_transform=100
export CUDA_VISIBLE_DEVICES=4; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=3 --env_type=smooth --dataset_composition=mixed_limited --cql_alpha_val=10 --transform_type=7 --const_transform=100
export CUDA_VISIBLE_DEVICES=5; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=4 --env_type=smooth --dataset_composition=mixed_limited --cql_alpha_val=10 --transform_type=7 --const_transform=100
export CUDA_VISIBLE_DEVICES=6; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=5 --env_type=smooth --dataset_composition=mixed_limited --cql_alpha_val=10 --transform_type=7 --const_transform=100
export CUDA_VISIBLE_DEVICES=7; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=6 --env_type=smooth --dataset_composition=mixed_limited --cql_alpha_val=10 --transform_type=7 --const_transform=100


export CUDA_VISIBLE_DEVICES=0; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=3 --env_type=smooth --dataset_composition=random+optimal --cql_alpha_val=1 --transform_type=7 --const_transform=100
export CUDA_VISIBLE_DEVICES=1; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=4 --env_type=smooth --dataset_composition=random+optimal --cql_alpha_val=1 --transform_type=7 --const_transform=100
export CUDA_VISIBLE_DEVICES=2; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=5 --env_type=smooth --dataset_composition=random+optimal --cql_alpha_val=1 --transform_type=7 --const_transform=100
export CUDA_VISIBLE_DEVICES=3; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=6 --env_type=smooth --dataset_composition=random+optimal --cql_alpha_val=1 --transform_type=7 --const_transform=100
export CUDA_VISIBLE_DEVICES=4; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=3 --env_type=smooth --dataset_composition=mixed_limited --cql_alpha_val=1 --transform_type=7 --const_transform=100
export CUDA_VISIBLE_DEVICES=5; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=4 --env_type=smooth --dataset_composition=mixed_limited --cql_alpha_val=1 --transform_type=7 --const_transform=100
export CUDA_VISIBLE_DEVICES=6; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=5 --env_type=smooth --dataset_composition=mixed_limited --cql_alpha_val=1 --transform_type=7 --const_transform=100
export CUDA_VISIBLE_DEVICES=7; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=6 --env_type=smooth --dataset_composition=mixed_limited --cql_alpha_val=1 --transform_type=7 --const_transform=100
export CUDA_VISIBLE_DEVICES=4; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=3 --env_type=smooth --dataset_composition=mixed_limited_skewed --cql_alpha_val=1 --transform_type=7 --const_transform=100
export CUDA_VISIBLE_DEVICES=5; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=4 --env_type=smooth --dataset_composition=mixed_limited_skewed --cql_alpha_val=1 --transform_type=7 --const_transform=100
export CUDA_VISIBLE_DEVICES=6; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=5 --env_type=smooth --dataset_composition=mixed_limited_skewed --cql_alpha_val=1 --transform_type=7 --const_transform=100
export CUDA_VISIBLE_DEVICES=7; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=6 --env_type=smooth --dataset_composition=mixed_limited_skewed --cql_alpha_val=1 --transform_type=7 --const_transform=100