export CUDA_VISIBLE_DEVICES=0; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=0 --env_type=smooth --dataset_composition=random+optimal --cql_alpha_val=1 --transform_type=0 --const_transform=4
export CUDA_VISIBLE_DEVICES=1; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=1 --env_type=smooth --dataset_composition=random+optimal --cql_alpha_val=1 --transform_type=0 --const_transform=4

export CUDA_VISIBLE_DEVICES=0; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=0 --env_type=smooth --dataset_composition=random+optimal --cql_alpha_val=.1 --transform_type=7 --const_transform=4
export CUDA_VISIBLE_DEVICES=1; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=1 --env_type=smooth --dataset_composition=random+optimal --cql_alpha_val=.1 --transform_type=7 --const_transform=4
export CUDA_VISIBLE_DEVICES=2; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=0 --env_type=smooth --dataset_composition=random+optimal --cql_alpha_val=.1 --transform_type=7 --const_transform=8
export CUDA_VISIBLE_DEVICES=3; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=1 --env_type=smooth --dataset_composition=random+optimal --cql_alpha_val=.1 --transform_type=7 --const_transform=8
export CUDA_VISIBLE_DEVICES=4; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=0 --env_type=smooth --dataset_composition=random+optimal --cql_alpha_val=1 --transform_type=7 --const_transform=4
export CUDA_VISIBLE_DEVICES=5; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=1 --env_type=smooth --dataset_composition=random+optimal --cql_alpha_val=1 --transform_type=7 --const_transform=4
export CUDA_VISIBLE_DEVICES=6; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=0 --env_type=smooth --dataset_composition=random+optimal --cql_alpha_val=1 --transform_type=7 --const_transform=8
export CUDA_VISIBLE_DEVICES=7; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=1 --env_type=smooth --dataset_composition=random+optimal --cql_alpha_val=1 --transform_type=7 --const_transform=8

export CUDA_VISIBLE_DEVICES=0; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=0 --env_type=smooth --dataset_composition=random+optimal --cql_alpha_val=.1 --transform_type=8 --const_transform=4
export CUDA_VISIBLE_DEVICES=1; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=1 --env_type=smooth --dataset_composition=random+optimal --cql_alpha_val=.1 --transform_type=8 --const_transform=4
export CUDA_VISIBLE_DEVICES=2; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=0 --env_type=smooth --dataset_composition=random+optimal --cql_alpha_val=.1 --transform_type=8 --const_transform=8
export CUDA_VISIBLE_DEVICES=3; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=1 --env_type=smooth --dataset_composition=random+optimal --cql_alpha_val=.1 --transform_type=8 --const_transform=8
export CUDA_VISIBLE_DEVICES=4; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=0 --env_type=smooth --dataset_composition=random+optimal --cql_alpha_val=1 --transform_type=8 --const_transform=4
export CUDA_VISIBLE_DEVICES=5; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=1 --env_type=smooth --dataset_composition=random+optimal --cql_alpha_val=1 --transform_type=8 --const_transform=4
export CUDA_VISIBLE_DEVICES=6; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=0 --env_type=smooth --dataset_composition=random+optimal --cql_alpha_val=1 --transform_type=8 --const_transform=8
export CUDA_VISIBLE_DEVICES=7; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=1 --env_type=smooth --dataset_composition=random+optimal --cql_alpha_val=1 --transform_type=8 --const_transform=8

export CUDA_VISIBLE_DEVICES=0; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=0 --env_type=smooth --dataset_composition=random+optimal --cql_alpha_val=.1 --transform_type=9 --const_transform=4
export CUDA_VISIBLE_DEVICES=1; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=1 --env_type=smooth --dataset_composition=random+optimal --cql_alpha_val=.1 --transform_type=9 --const_transform=4
export CUDA_VISIBLE_DEVICES=2; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=0 --env_type=smooth --dataset_composition=random+optimal --cql_alpha_val=.1 --transform_type=9 --const_transform=8
export CUDA_VISIBLE_DEVICES=3; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=1 --env_type=smooth --dataset_composition=random+optimal --cql_alpha_val=.1 --transform_type=9 --const_transform=8
export CUDA_VISIBLE_DEVICES=4; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=0 --env_type=smooth --dataset_composition=random+optimal --cql_alpha_val=1 --transform_type=9 --const_transform=4
export CUDA_VISIBLE_DEVICES=5; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=1 --env_type=smooth --dataset_composition=random+optimal --cql_alpha_val=1 --transform_type=9 --const_transform=4
export CUDA_VISIBLE_DEVICES=6; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=0 --env_type=smooth --dataset_composition=random+optimal --cql_alpha_val=1 --transform_type=9 --const_transform=8
export CUDA_VISIBLE_DEVICES=7; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=1 --env_type=smooth --dataset_composition=random+optimal --cql_alpha_val=1 --transform_type=9 --const_transform=8

export CUDA_VISIBLE_DEVICES=0; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=0 --env_type=smooth --dataset_composition=random+optimal --cql_alpha_val=.1 --transform_type=10 --const_transform=4
export CUDA_VISIBLE_DEVICES=1; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=1 --env_type=smooth --dataset_composition=random+optimal --cql_alpha_val=.1 --transform_type=10 --const_transform=4
export CUDA_VISIBLE_DEVICES=2; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=0 --env_type=smooth --dataset_composition=random+optimal --cql_alpha_val=.1 --transform_type=10 --const_transform=8
export CUDA_VISIBLE_DEVICES=3; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=1 --env_type=smooth --dataset_composition=random+optimal --cql_alpha_val=.1 --transform_type=10 --const_transform=8
export CUDA_VISIBLE_DEVICES=4; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=0 --env_type=smooth --dataset_composition=random+optimal --cql_alpha_val=1 --transform_type=10 --const_transform=4
export CUDA_VISIBLE_DEVICES=5; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=1 --env_type=smooth --dataset_composition=random+optimal --cql_alpha_val=1 --transform_type=10 --const_transform=4
export CUDA_VISIBLE_DEVICES=6; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=0 --env_type=smooth --dataset_composition=random+optimal --cql_alpha_val=1 --transform_type=10 --const_transform=8
export CUDA_VISIBLE_DEVICES=7; conda activate SimpleSAC; python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=1 --env_type=smooth --dataset_composition=random+optimal --cql_alpha_val=1 --transform_type=10 --const_transform=8