python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=3 --env_type=smooth --dataset_composition=mixed_limited --cql_alpha_val=1 --transform_type=13 --const_transform=1 --exp_start vals --load_network /home/asap7772/asap7772/algo_gridworld/data/relaunch_maze3_datasetmixed_limited_size100_envsmooth_minq1.0_ttype0_const1.0 --loadnoinit --othernet &
python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=4 --env_type=smooth --dataset_composition=mixed_limited --cql_alpha_val=1 --transform_type=13 --const_transform=1 --exp_start vals --load_network /home/asap7772/asap7772/algo_gridworld/data/relaunch_maze4_datasetmixed_limited_size100_envsmooth_minq1.0_ttype0_const1.0 --loadnoinit --othernet & 
python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=5 --env_type=smooth --dataset_composition=mixed_limited --cql_alpha_val=1 --transform_type=13 --const_transform=1 --exp_start vals --load_network /home/asap7772/asap7772/algo_gridworld/data/relaunch_maze5_datasetmixed_limited_size100_envsmooth_minq1.0_ttype0_const1.0 --loadnoinit --othernet &
python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=6 --env_type=smooth --dataset_composition=mixed_limited --cql_alpha_val=1 --transform_type=13 --const_transform=1 --exp_start vals --load_network /home/asap7772/asap7772/algo_gridworld/data/relaunch_maze6_datasetmixed_limited_size100_envsmooth_minq1.0_ttype0_const1.0 --loadnoinit --othernet &

python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=3 --env_type=smooth --dataset_composition=mixed_limited --cql_alpha_val=1 --transform_type=13 --const_transform=10 --exp_start vals --load_network /home/asap7772/asap7772/algo_gridworld/data/relaunch_maze3_datasetmixed_limited_size100_envsmooth_minq1.0_ttype0_const1.0 --loadnoinit --othernet &
python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=4 --env_type=smooth --dataset_composition=mixed_limited --cql_alpha_val=1 --transform_type=13 --const_transform=10 --exp_start vals --load_network /home/asap7772/asap7772/algo_gridworld/data/relaunch_maze4_datasetmixed_limited_size100_envsmooth_minq1.0_ttype0_const1.0 --loadnoinit --othernet & 
python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=5 --env_type=smooth --dataset_composition=mixed_limited --cql_alpha_val=1 --transform_type=13 --const_transform=10 --exp_start vals --load_network /home/asap7772/asap7772/algo_gridworld/data/relaunch_maze5_datasetmixed_limited_size100_envsmooth_minq1.0_ttype0_const1.0 --loadnoinit --othernet &
python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=6 --env_type=smooth --dataset_composition=mixed_limited --cql_alpha_val=1 --transform_type=13 --const_transform=10 --exp_start vals --load_network /home/asap7772/asap7772/algo_gridworld/data/relaunch_maze6_datasetmixed_limited_size100_envsmooth_minq1.0_ttype0_const1.0 --loadnoinit --othernet &

python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=3 --env_type=smooth --dataset_composition=mixed_limited --cql_alpha_val=1 --transform_type=13 --const_transform=100 --exp_start vals --load_network /home/asap7772/asap7772/algo_gridworld/data/relaunch_maze3_datasetmixed_limited_size100_envsmooth_minq1.0_ttype0_const1.0 --loadnoinit --othernet &
python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=4 --env_type=smooth --dataset_composition=mixed_limited --cql_alpha_val=1 --transform_type=13 --const_transform=100 --exp_start vals --load_network /home/asap7772/asap7772/algo_gridworld/data/relaunch_maze4_datasetmixed_limited_size100_envsmooth_minq1.0_ttype0_const1.0 --loadnoinit --othernet & 
python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=5 --env_type=smooth --dataset_composition=mixed_limited --cql_alpha_val=1 --transform_type=13 --const_transform=100 --exp_start vals --load_network /home/asap7772/asap7772/algo_gridworld/data/relaunch_maze5_datasetmixed_limited_size100_envsmooth_minq1.0_ttype0_const1.0 --loadnoinit --othernet &
python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=6 --env_type=smooth --dataset_composition=mixed_limited --cql_alpha_val=1 --transform_type=13 --const_transform=100 --exp_start vals --load_network /home/asap7772/asap7772/algo_gridworld/data/relaunch_maze6_datasetmixed_limited_size100_envsmooth_minq1.0_ttype0_const1.0 --loadnoinit --othernet &

#-----------------------------------------------------------------------------------------------------------------------

python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=3 --env_type=smooth --dataset_composition=mixed_limited --cql_alpha_val=10 --transform_type=13 --const_transform=1 --exp_start vals --load_network /home/asap7772/asap7772/algo_gridworld/data/relaunch_maze3_datasetmixed_limited_size100_envsmooth_minq10.0_ttype0_const1.0 --loadnoinit --othernet &
python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=4 --env_type=smooth --dataset_composition=mixed_limited --cql_alpha_val=10 --transform_type=13 --const_transform=1 --exp_start vals --load_network /home/asap7772/asap7772/algo_gridworld/data/relaunch_maze4_datasetmixed_limited_size100_envsmooth_minq10.0_ttype0_const1.0 --loadnoinit --othernet &
python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=5 --env_type=smooth --dataset_composition=mixed_limited --cql_alpha_val=10 --transform_type=13 --const_transform=1 --exp_start vals --load_network /home/asap7772/asap7772/algo_gridworld/data/relaunch_maze5_datasetmixed_limited_size100_envsmooth_minq10.0_ttype0_const1.0 --loadnoinit --othernet &
python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=6 --env_type=smooth --dataset_composition=mixed_limited --cql_alpha_val=10 --transform_type=13 --const_transform=1 --exp_start vals --load_network /home/asap7772/asap7772/algo_gridworld/data/relaunch_maze6_datasetmixed_limited_size100_envsmooth_minq10.0_ttype0_const1.0 --loadnoinit --othernet &

python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=3 --env_type=smooth --dataset_composition=mixed_limited --cql_alpha_val=10 --transform_type=13 --const_transform=10 --exp_start vals --load_network /home/asap7772/asap7772/algo_gridworld/data/relaunch_maze3_datasetmixed_limited_size100_envsmooth_minq10.0_ttype0_const1.0 --loadnoinit --othernet &
python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=4 --env_type=smooth --dataset_composition=mixed_limited --cql_alpha_val=10 --transform_type=13 --const_transform=10 --exp_start vals --load_network /home/asap7772/asap7772/algo_gridworld/data/relaunch_maze4_datasetmixed_limited_size100_envsmooth_minq10.0_ttype0_const1.0 --loadnoinit --othernet &
python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=5 --env_type=smooth --dataset_composition=mixed_limited --cql_alpha_val=10 --transform_type=13 --const_transform=10 --exp_start vals --load_network /home/asap7772/asap7772/algo_gridworld/data/relaunch_maze5_datasetmixed_limited_size100_envsmooth_minq10.0_ttype0_const1.0 --loadnoinit --othernet &
python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=6 --env_type=smooth --dataset_composition=mixed_limited --cql_alpha_val=10 --transform_type=13 --const_transform=10 --exp_start vals --load_network /home/asap7772/asap7772/algo_gridworld/data/relaunch_maze6_datasetmixed_limited_size100_envsmooth_minq10.0_ttype0_const1.0 --loadnoinit --othernet &

python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=3 --env_type=smooth --dataset_composition=mixed_limited --cql_alpha_val=10 --transform_type=13 --const_transform=100 --exp_start vals --load_network /home/asap7772/asap7772/algo_gridworld/data/relaunch_maze3_datasetmixed_limited_size100_envsmooth_minq10.0_ttype0_const1.0 --loadnoinit --othernet &
python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=4 --env_type=smooth --dataset_composition=mixed_limited --cql_alpha_val=10 --transform_type=13 --const_transform=100 --exp_start vals --load_network /home/asap7772/asap7772/algo_gridworld/data/relaunch_maze4_datasetmixed_limited_size100_envsmooth_minq10.0_ttype0_const1.0 --loadnoinit --othernet &
python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=5 --env_type=smooth --dataset_composition=mixed_limited --cql_alpha_val=10 --transform_type=13 --const_transform=100 --exp_start vals --load_network /home/asap7772/asap7772/algo_gridworld/data/relaunch_maze5_datasetmixed_limited_size100_envsmooth_minq10.0_ttype0_const1.0 --loadnoinit --othernet &
python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=6 --env_type=smooth --dataset_composition=mixed_limited --cql_alpha_val=10 --transform_type=13 --const_transform=100 --exp_start vals --load_network /home/asap7772/asap7772/algo_gridworld/data/relaunch_maze6_datasetmixed_limited_size100_envsmooth_minq10.0_ttype0_const1.0 --loadnoinit --othernet &

#-----------------------------------------------------------------------------------------------------------------------

python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=3 --env_type=smooth --dataset_composition=mixed_limited --cql_alpha_val=100 --transform_type=13 --const_transform=1 --exp_start vals --load_network /home/asap7772/asap7772/algo_gridworld/data/relaunch_maze3_datasetmixed_limited_size100_envsmooth_minq100.0_ttype0_const1.0 --loadnoinit --othernet &
python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=4 --env_type=smooth --dataset_composition=mixed_limited --cql_alpha_val=100 --transform_type=13 --const_transform=1 --exp_start vals --load_network /home/asap7772/asap7772/algo_gridworld/data/relaunch_maze4_datasetmixed_limited_size100_envsmooth_minq100.0_ttype0_const1.0 --loadnoinit --othernet &
python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=5 --env_type=smooth --dataset_composition=mixed_limited --cql_alpha_val=100 --transform_type=13 --const_transform=1 --exp_start vals --load_network /home/asap7772/asap7772/algo_gridworld/data/relaunch_maze5_datasetmixed_limited_size100_envsmooth_minq100.0_ttype0_const1.0 --loadnoinit --othernet &
python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=6 --env_type=smooth --dataset_composition=mixed_limited --cql_alpha_val=100 --transform_type=13 --const_transform=1 --exp_start vals --load_network /home/asap7772/asap7772/algo_gridworld/data/relaunch_maze6_datasetmixed_limited_size100_envsmooth_minq100.0_ttype0_const1.0 --loadnoinit --othernet &

python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=3 --env_type=smooth --dataset_composition=mixed_limited --cql_alpha_val=100 --transform_type=13 --const_transform=10 --exp_start vals --load_network /home/asap7772/asap7772/algo_gridworld/data/relaunch_maze3_datasetmixed_limited_size100_envsmooth_minq100.0_ttype0_const1.0 --loadnoinit --othernet &
python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=4 --env_type=smooth --dataset_composition=mixed_limited --cql_alpha_val=100 --transform_type=13 --const_transform=10 --exp_start vals --load_network /home/asap7772/asap7772/algo_gridworld/data/relaunch_maze4_datasetmixed_limited_size100_envsmooth_minq100.0_ttype0_const1.0 --loadnoinit --othernet &
python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=5 --env_type=smooth --dataset_composition=mixed_limited --cql_alpha_val=100 --transform_type=13 --const_transform=10 --exp_start vals --load_network /home/asap7772/asap7772/algo_gridworld/data/relaunch_maze5_datasetmixed_limited_size100_envsmooth_minq100.0_ttype0_const1.0 --loadnoinit --othernet &
python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=6 --env_type=smooth --dataset_composition=mixed_limited --cql_alpha_val=100 --transform_type=13 --const_transform=10 --exp_start vals --load_network /home/asap7772/asap7772/algo_gridworld/data/relaunch_maze6_datasetmixed_limited_size100_envsmooth_minq100.0_ttype0_const1.0 --loadnoinit --othernet &

python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=3 --env_type=smooth --dataset_composition=mixed_limited --cql_alpha_val=100 --transform_type=13 --const_transform=100 --exp_start vals --load_network /home/asap7772/asap7772/algo_gridworld/data/relaunch_maze3_datasetmixed_limited_size100_envsmooth_minq100.0_ttype0_const1.0 --loadnoinit --othernet &
python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=4 --env_type=smooth --dataset_composition=mixed_limited --cql_alpha_val=100 --transform_type=13 --const_transform=100 --exp_start vals --load_network /home/asap7772/asap7772/algo_gridworld/data/relaunch_maze4_datasetmixed_limited_size100_envsmooth_minq100.0_ttype0_const1.0 --loadnoinit --othernet &
python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=5 --env_type=smooth --dataset_composition=mixed_limited --cql_alpha_val=100 --transform_type=13 --const_transform=100 --exp_start vals --load_network /home/asap7772/asap7772/algo_gridworld/data/relaunch_maze5_datasetmixed_limited_size100_envsmooth_minq100.0_ttype0_const1.0 --loadnoinit --othernet &
python /home/asap7772/asap7772/algo_gridworld/offline_rl_gridworld.py --maze_type=6 --env_type=smooth --dataset_composition=mixed_limited --cql_alpha_val=100 --transform_type=13 --const_transform=100 --exp_start vals --load_network /home/asap7772/asap7772/algo_gridworld/data/relaunch_maze6_datasetmixed_limited_size100_envsmooth_minq100.0_ttype0_const1.0 --loadnoinit --othernet &

